"""add image public id field

Revision ID: 17082ebc20ae
Revises: 14f4a8031a6d
Create Date: 2026-08-27 03:18:37.738509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17082ebc20ae'
down_revision: Union[str, Sequence[str], None] = '14f4a8031a6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_public_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_public_id')
    # ### end Alembic commands ###
