"""add contact info

Revision ID: 9564b3aadbe2
Revises: b158a995ca9b
Create Date: 2026-08-25 23:14:31.274751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9564b3aadbe2'
down_revision: Union[str, Sequence[str], None] = 'b158a995ca9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'contact_number')
    # Add contact_number with a temporary server default so existing rows get a non-null value
    op.add_column(
        'users',
        sa.Column('contact_number', sa.String(), nullable=False, server_default=sa.text("''"))
    )
    # Remove the server default now that the column is populated
    op.execute("ALTER TABLE users ALTER COLUMN contact_number DROP DEFAULT")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'contact_number')
    op.add_column('products', sa.Column('contact_number', sa.String(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
