"""add token version and contact details

Revision ID: b158a995ca9b
Revises: 062aec56e9df
Create Date: 2026-08-25 21:22:48.508629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b158a995ca9b'
down_revision: Union[str, Sequence[str], None] = '062aec56e9df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('token_version', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'token_version')
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
